//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vinculacion
    {
        public int idvinculacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string nombre_organizacion { get; set; }
        public string nombre_responsable { get; set; }
        public Nullable<int> numero_horas { get; set; }
        public string nombre_proyecto { get; set; }
        public Nullable<int> numero_integrantes { get; set; }
        public string ubicacion { get; set; }
    }
}
